//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airline
    {
        public Airline()
        {
            this.Airplanes = new HashSet<Airplane>();
        }
    
        public int AirlineID { get; set; }
        public string Airline_name { get; set; }
        public string Airline_country { get; set; }
        public string Destination { get; set; }
    
        public virtual ICollection<Airplane> Airplanes { get; set; }
    }
}
