//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airport
    {
        public Airport()
        {
            this.Flights = new HashSet<Flight>();
        }
    
        public int AirportID { get; set; }
        public string Airport_name { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Numberofrunways { get; set; }
    
        public virtual ICollection<Flight> Flights { get; set; }
    }
}
