//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airplane
    {
        public int AirplaneID { get; set; }
        public string Airplane_name { get; set; }
        public string Variant { get; set; }
        public string Crew_size { get; set; }
        public Nullable<int> AirlineID { get; set; }
    
        public virtual Airline Airline { get; set; }
    }
}
